### ISSUE TITLE
Foundation npm not able to work

### ISSUE THREAD

**Issue by rony925** [bradtraversy/bthosting_foundation#1]
just installed node v8.9 and tried to configure foundation but get the following error

Rony@DESKTOP-BKUSE1J MINGW64 ~/Documents
$ npm install foundation-cli --global
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any m                      oment because its dependencies can change. Prevent this by migrating to Yarn: ht                      tps://bower.io/blog/2017/how-to-migrate-away-from-bower/
C:\Users\Rony\AppData\Roaming\npm\foundation -> C:\Users\Rony\AppData\Roaming\npm\node_mo             dules\foundation-cli\bin\foundation.js
+ foundation-cli@2.2.5
updated 1 package in 23.216s

Rony@DESKTOP-BKUSE1J MINGW64 ~/Documents
$ foundation new --framework sites --template basic
? What's the project called? (no spaces) kdplazaasr

            .
           /|     ,
      , /|/  \/| /|       Thanks for using ZURB Foundation for Sites!
     /|/       |/ |       -------------------------------------------
 |___|            |___|   Let's set up a new project.
 \___|  ^^   ^^   |___/   It shouldn't take more than a minute.
     | -[O]--[O]- |
     |    ___,    |
     |    ...     |
      \__________/

Downloading the project template...
Done downloading!

Installing dependencies...

> node-sass@3.13.1 install C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sass\node             _modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32             -x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57             _binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sass\             node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\Rony\Documents\kdplazaasr\node_module             s\gulp-sass\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbos             e --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Rony\\Documents\\kdplazaasr\\node_modules\\gulp-sass\\node_mod             ules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Rony\Documents\kdplazaasr\node_             modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.j             s:13:12)
gyp verb `which` failed     at F (C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sa             ss\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sa             ss\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sass\             node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sass\             node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\index.             js:42:5
gyp verb `which` failed     at C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sass\             node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\window             s.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Rony\Documents\kdplazaasr\node_             modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.j             s:13:12)
gyp verb `which` failed     at F (C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sa             ss\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sa             ss\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sass\             node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sass\             node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\index.             js:42:5
gyp verb `which` failed     at C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sass\             node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\window             s.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\             \Users\\Rony\\Documents\\kdplazaasr\\node_modules\\gulp-sass\\node_modules\\node-sass\\no             de_modules\\node-gyp\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\Rony\\Do             cuments\\kdplazaasr\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\node             -gyp\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Rony\\Documents\\kdplaza             asr\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\node-gyp\\node_modul             es\\which\\which.js:80:29)\n    at C:\\Users\\Rony\\Documents\\kdplazaasr\\node_modules\\             gulp-sass\\node_modules\\node-sass\\node_modules\\node-gyp\\node_modules\\which\\which.js             :89:16\n    at C:\\Users\\Rony\\Documents\\kdplazaasr\\node_modules\\gulp-sass\\node_modu             les\\node-sass\\node_modules\\node-gyp\\node_modules\\which\\node_modules\\isexe\\index.j             s:42:5\n    at C:\\Users\\Rony\\Documents\\kdplazaasr\\node_modules\\gulp-sass\\node_modu             les\\node-sass\\node_modules\\node-gyp\\node_modules\\which\\node_modules\\isexe\\windows             .js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Rony\Documents\kdplazaasr\node_             modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.j             s:13:12)
gyp verb `which` failed     at F (C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sa             ss\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sa             ss\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sass\             node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sass\             node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\index.             js:42:5
gyp verb `which` failed     at C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sass\             node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\window             s.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Rony\Documents\kdplazaasr\node_             modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.j             s:13:12)
gyp verb `which` failed     at F (C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sa             ss\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sa             ss\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sass\             node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sass\             node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\index.             js:42:5
gyp verb `which` failed     at C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sass\             node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\window             s.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\             Users\\Rony\\Documents\\kdplazaasr\\node_modules\\gulp-sass\\node_modules\\node-sass\\nod             e_modules\\node-gyp\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\Rony\\Doc             uments\\kdplazaasr\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\node-             gyp\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Rony\\Documents\\kdplazaa             sr\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\node-gyp\\node_module             s\\which\\which.js:80:29)\n    at C:\\Users\\Rony\\Documents\\kdplazaasr\\node_modules\\g             ulp-sass\\node_modules\\node-sass\\node_modules\\node-gyp\\node_modules\\which\\which.js:             89:16\n    at C:\\Users\\Rony\\Documents\\kdplazaasr\\node_modules\\gulp-sass\\node_modul             es\\node-sass\\node_modules\\node-gyp\\node_modules\\which\\node_modules\\isexe\\index.js             :42:5\n    at C:\\Users\\Rony\\Documents\\kdplazaasr\\node_modules\\gulp-sass\\node_modul             es\\node-sass\\node_modules\\node-gyp\\node_modules\\which\\node_modules\\isexe\\windows.             js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env v             ariable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Rony\Documents\kdplazaasr\node_             modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Rony\Documents\kdplazaasr\node_m             odules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sass\node_modu             les\node-sass\node_modules\node-gyp\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Rony\\Documents\\kdpla             zaasr\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\nod             e-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="              "--libsass_library="
gyp ERR! cwd C:\Users\Rony\Documents\kdplazaasr\node_modules\gulp-sass\node_modules\node-             sass
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1

There were some problems during the installation.

 ✓ New project folder created.
 ✗ Node modules not installed. Try running npm install manually.
 ✓ Bower components installed.

Once you've resolved the above issues, run foundation watch while inside the kdplazaasr f             older.

I would apprecite if you can help me out.
I am totally new to foundation.
Thanks
Rony

**Comment by fr4ngus** [comment]
node-gyp needs python2 see: [https://github.com/nodejs/node-gyp](url)
